@startuml

title __DIALOG's Class Diagram__\n

  package com.lt.personal_stadiumbookingsystem {
    package com.lt.personal_stadiumbookingsystem.ui.dialog {
      class ConfirmDialog {
          - mMessage : String
          {static} + newInstance()
          + onCreate()
          # setLayoutResId()
          # setAgreeButtonId()
          # setDenyButtonId()
          # initView()
      }
    }
  }
  

  ConfirmDialog -up-|> BaseDialog
  SavedState -up-|> Parcelable


right footer

endfooter

@enduml
